sudo: required
dist: trusty
language: c
matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - rpm
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils;
  - sudo snap install snapcraft --classic;
  - sudo apt-get install rpm -y;
install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe
  - yarn
before_script:
  - git lfs pull
script:
  - yarn release
branches:
  only:
    - master
notifications:
  email: false
