sudo: required
dist: xenial
language: c
matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
cache:
  directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - rpm
before_install:
  - sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
  - sudo snap install snapcraft --classic; fi
install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe
  - yarn
before_script:
  - git lfs pull
script:
  - yarn release
branches:
  only:
    - master
deploy:
  provider: snap
  snap: koodo-reader.snap
  channel: edge
  skip_cleanup: true
notifications:
  email: false
