version: 0.1.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2019
  - macos

stack: node 10

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - git reset --hard HEAD
  - npm install
  - node --version

build_script:
  - npm run release

test: off
