version: 0.1.{build}

branches:
  only:
    - master

image:
  #  - Visual Studio 2019
  #  - macos
  - Ubuntu

stack: node 10

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input
  - sh: |
      if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu" ]
      then
        sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
        sudo apt-get install snapd
        sudo apt-get install -y rpm
      fi

install:
  - git reset --hard HEAD
  - npm install
  - node --version

before_build:
  - node --version
  - npm --version
  # Get new $SNAP_TOKEN with:
  # $ snapcraft export-login --snaps bw --acls package_push,package_release -
  - sh: |
      if [ "${SNAP_TOKEN}" != "" ]
      then
        sudo snap install snapcraft --classic
        echo "$SNAP_TOKEN" | snapcraft login --with -
      fi

build_script:
  - npm run release

test: off
