version: 0.1.{build}

branches:
  only:
    - master

image:
  - Visual Studio 2019
  - macos
  - Ubuntu

stack: node 10

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

before_install:
  - sh: |
      if [ "${APPVEYOR_BUILD_WORKER_IMAGE}" == "Ubuntu" ]
      then
        sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
        sudo apt-get -y install snapd
        sudo snap -y install snapcraft --classic
      fi

install:
  - git reset --hard HEAD
  - npm install
  - node --version

build_script:
  - npm run release

test: off
