version: 0.1.{build}

branches:
  only:
    - master

image:
  - macos
  - Visual Studio 2019
  - Ubuntu

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn release

test: off
