name: 功能建议
description: 我希望 Koodo Reader 增加这个功能
labels: "feature request"
body:
  - type: textarea
    id: introduction
    attributes:
      label: 简单介绍
      placeholder: 关于这个需求的简单介绍
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: 细节描述
      placeholder: 关于这个需求的细节描述
    validations:
      required: true
